wip: fixup patchnewgtlds script

diff --git a/tools/patchnewgtlds b/tools/patchnewgtlds
--- a/tools/patchnewgtlds
+++ b/tools/patchnewgtlds
@@ -20,10 +20,10 @@ then
   popd
 fi
 
-#if ! [ -x "$(command $BIN_CMD)" ]
-#then
-#  echo "installed Go tools module but $BIN_CMD not found on \$PATH..." >&2
-#  exit 1
-#fi
+if ! [ -x "$(command $BIN_CMD)" ]
+then
+  echo "installed Go tools module but $BIN_CMD not found on \$PATH..." >&2
+  exit 1
+fi
 
-~/go/bin/newgtlds -overwrite -psl-dat-file="$PROJECT_ROOT/public_suffix_list.dat"
+newgtlds -overwrite -psl-dat-file="$PROJECT_ROOT/public_suffix_list.dat"
